plugin:
    name: 'initbiz.cumuluscore::lang.plugin.name'
    description: 'initbiz.cumuluscore::lang.plugin.description'
    author: Initbiz
    icon: oc-icon-soundcloud
    homepage: 'http://cumulus.init.biz'
navigation:
    cumulus-main-menu:
        label: 'initbiz.cumuluscore::lang.navigation.main'
        url: initbiz/cumuluscore/users
        icon: icon-soundcloud
        order: '700'
        sideMenu:
            cumulus-side-menu-users:
                label: 'initbiz.cumuluscore::lang.navigation.users'
                url: initbiz/cumuluscore/users
                icon: icon-users
            cumulus-side-menu-clusters:
                label: 'initbiz.cumuluscore::lang.navigation.clusters'
                url: initbiz/cumuluscore/clusters
                icon: icon-yelp
            cumulus-side-menu-plan:
                label: 'initbiz.cumuluscore::lang.navigation.plans'
                url: initbiz/cumuluscore/plans
                icon: icon-codepen
