name: Plans
form: $/initbiz/cumuluscore/models/plan/fields.yaml
modelClass: InitBiz\CumulusCore\Models\Plan
defaultRedirect: initbiz/cumuluscore/plans
create:
    redirect: 'initbiz/cumuluscore/plans/update/:plan_id'
    redirectClose: initbiz/cumuluscore/plans
update:
    redirect: initbiz/cumuluscore/plans
    redirectClose: initbiz/cumuluscore/plans
