# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/initbiz/cumuluscore/models/module/columns.yaml

# Model Class name
modelClass: Initbiz\CumulusCore\Models\Module

# List Title
title: Manage Modules

# Link URL for each record
#recordUrl: initbiz/cumuluscore/modules/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

## Toolbar widget configuration
#toolbar:
#
#    # Search widget configuration
#    search:
#        prompt: backend::lang.list.search_prompt
