name: Companies
modelClass: InitBiz\CumulusCore\Models\Company
form: $/initbiz/cumuluscore/models/company/fields.yaml
defaultRedirect: initbiz/cumuluscore/companies
create:
    redirect: 'initbiz/cumuluscore/companies/update/:company_id'
    redirectClose: initbiz/cumuluscore/companies
update:
    redirect: initbiz/cumuluscore/companies
    redirectClose: initbiz/cumuluscore/companies
preview: {  }
